# Generated by Django 4.2.19 on 2025-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='hypotheses',
            field=models.TextField(blank=True),
        ),
    ]
